### ISSUE TITLE
sakura internetさんのロゴをセンターに表示させる

### ISSUE THREAD

**Issue by nyampire** [osmfj/osmfj-website#10]
どこで変更するのか調べる

**Comment by KMR-zoar** [comment]
あまり大きく変更しない形であれば[ロゴの親要素のdiv](https://github.com/nyampire/agency-jekyll-theme/blob/gh-pages/_includes/clients.html#L32)にオフセットのclassを追加してあげるとセンターに動きました。

```html
<div class="col-md-3 col-sm-6">
 ↓
<div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-3">
```

オフセットにつけた数字はbootstrapのグリッドシステムの12からcol-sm-**6**の6を引いて2で割った数字です。
col-md-3だとオフセットが4.5になりますが、col-dm-offset-4.5はないのでcol-md-4にした上でcol-md-offset-4を使った形です。この場合ちょっとロゴが大きくなります。

**Comment by nyampire** [comment]
ありがとうございます。
4467f14dafab5d27b9eeee1c32f7505c79b65eed で対応しました！
