### ISSUE TITLE
OSMFJのリポジトリに移管する

### ISSUE THREAD

**Issue by nyampire** [osmfj/osmfj-website#14]
リポジトリの移管と公開作業のための手順を洗い出す

**Comment by miurahr** [comment]
移管をさきにおねがいします。
settings -> danger zone -> 移管 
github.com/osmfj にいって、リポジトリ名を osmfj_website に変更

公開作業は、ssl設定が必要ですね。

**Comment by nyampire** [comment]
移管しました。
あと、osmfj-website (ハイフン) にしちゃった。もし必須であればまた修正ですね。
