### ISSUE TITLE
リンク先の定款がふるい

### ISSUE THREAD

**Issue by miurahr** [osmfj/osmfj-website#22]
最初の定款がリンクされており、現行でないようだ。
https://wiki.openstreetmap.org/wiki/OSMFJ/bylaws

Wikiのリンクの修正が必要

**Comment by KMR-zoar** [comment]
定款を更新しました。

新しい定款の PDF ファイルは `マイドライブ > OSMFJ > 事務局 > 定款` に保存されています。
