### ISSUE TITLE
DNSのひきさきがおかしい(osmf.jp)

### ISSUE THREAD

**Issue by miurahr** [osmfj/osmfj-website#30]
www.osmf.jp だとただしいサイトが表示されるが、 https://osmf.jp/ だと、 https://openstreetmap.jp/ に誘導される

**Comment by nyampire** [comment]
以下の設定をDNS設定として追加。
osmf.jp にアクセスした場合でも www ありと同じサイトが表示される。
ただし、証明書のエラーがでるので、また別のIssueとして扱う。

```
a @ 185.199.108.153
a @ 185.199.109.153
a @ 185.199.110.153
a @ 185.199.111.153
```
