### ISSUE TITLE
「OSMFJについて」の部分の記事掲載順など

### ISSUE THREAD

**Issue by nyampire** [osmfj/osmfj-website#7]
記事の並び順がどのように制御されるか、いまいちわからない。

**Comment by KMR-zoar** [comment]
_postディレクトリの各マークダウン6行目にある`date`が新しいものが左上の方に表示されているっぽいです。
`date`の古いものから記事が作成されて新しいものが以前の記事よりも前方に追加されるので、`date`の日付が新しいものが左上、古いものが右下に並ぶようになる感じだと思います。

ファイルの内容

|markdown|date|
|:-:|:-:|
|project1|2018/04/10|
|project2|2100/01/01|
|project3|2018/03/31|
|project4|2014/07/15|
|project5|2017/10/11|

`date` で降順ソート  ↓

|markdown|date|
|:-:|:-:|
|project2|2100/01/01|
|project1|2018/04/10|
|project3|2018/03/31|
|project5|2017/10/11|
|project4|2014/07/15|

**Comment by nyampire** [comment]
ありがとうございます。
ほんとうはここは、プレスリリースとかの記事追加部分なのでそうなっちゃうのかな、と。ひとまずは挙動がわかったのでクローズしますー
